### ISSUE TITLE
RubyCocoa dependency cannot be installed on OS/X 10.7

### ISSUE THREAD

**Issue by drnic** [drnic/choctop#18]
I guess we need to remove the RubyCocoa dependency for OS/X 10.7 developers.

**Comment by billymeltdown** [comment]
Hi Nic,

I was just trying to use ChocTop on my 10.7 system, been a little bit: and I think I'm running into this. Would this problem cause the error output I see below when I try to use the Rakefile?

Thanks!
Billy

```
$ rake -T
(in /Users/billy/Documents/Sources/Cocoa/stripsync-mac)
rake aborted!
no such file to load -- osx/cocoa
/Users/billy/Documents/Sources/Cocoa/stripsync-mac/Rakefile:4:in `<main>'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/1.9.2/rake.rb:2374:in `raw_load_rakefile'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/1.9.2/rake.rb:2008:in `block'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/1.9.2/rake.rb:2059:in `standard_exception_handling'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/1.9.2/rake.rb:2007:in `load_rakefile'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/1.9.2/rake.rb:1992:in `run'
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/bin/macrake:31:in `<main>'
```

**Comment by billymeltdown** [comment]
Hm, perhaps this issue is unrelated to what I noted above. `rake -T` works just fine if I use /usr/bin/ruby (and not macruby via rvm).

**Comment by drnic** [comment]
I don't know what the solution to this is as the moment. I think we need to rip out RubyCocoa dependency.

**Comment by billymeltdown** [comment]
Well, fwiw, I haven't used choctop in at least a year, nice to just pick it up again and have it and that project still rocking, even with a much newer Xcode (I'm on 4.3.2). Cheers!

**Comment by drnic** [comment]
Just need to remove RubyCocoa. Want to figure out why we're using it? Perhaps 10.7 has something to place those dependencies. I can't remember why we're using except for plist (which I think there's a ruby gem for now)

**Comment by billymeltdown** [comment]
Sure, I'll take a look next week! 

B

**Comment by drnic** [comment]
Hurray!

**Comment by plukevdh** [comment]
Looking at this... Curious if any work has been done on it.
