### ISSUE TITLE
choctop is stacktracing on osx 10.8.5 and homebrew ruby

### ISSUE THREAD

**Issue by pallotron** [drnic/choctop#20]
Trying to use choctop on osx 10.8.5, getting the following exception:

```
pallotron@pallotron-mba:~ $ install_choctop projects/yubiswitch/
/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- rubigen (LoadError)
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/gems/2.0.0/gems/choctop-0.14.1/bin/install_choctop:4:in `<top (required)>'
    from /usr/local/opt/ruby/bin/install_choctop:23:in `load'
    from /usr/local/opt/ruby/bin/install_choctop:23:in `<main>'
```

Using ruby installed via homebrew.

```
pallotron@pallotron-mba:~ $ ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.5.0]
```

any idea what could be going wrong?

**Comment by pallotron** [comment]
guess ruby coming from homebrew doesn't have ruby cocoas installed. i stumbled across this -> http://rbxbx.tumblr.com/post/556343148/install-rubycocoa-on-rvm

will work on installing rvm

**Comment by pallotron** [comment]
updating to ruby-2.0.0-p247 via rvm isn't working either:

```
pallotron@pallotron-mba:~ $ rvm list

rvm rubies

 * ruby-1.8.7-p374 [ i686 ]
=> ruby-2.0.0-p247 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

pallotron@pallotron-mba:~ $ which ruby
/Users/pallotron/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
pallotron@pallotron-mba:~ $ which install_choctop
/Users/pallotron/.rvm/gems/ruby-2.0.0-p247/bin/install_choctop
pallotron@pallotron-mba:~ $ install_choctop projects/yubiswitch/
/Users/pallotron/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- rubigen (LoadError)
    from /Users/pallotron/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/pallotron/.rvm/gems/ruby-2.0.0-p247/gems/choctop-0.14.1/bin/install_choctop:4:in `<top (required)>'
    from /Users/pallotron/.rvm/gems/ruby-2.0.0-p247/bin/install_choctop:23:in `load'
    from /Users/pallotron/.rvm/gems/ruby-2.0.0-p247/bin/install_choctop:23:in `<main>'
    from /Users/pallotron/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
```

**Comment by pallotron** [comment]
I've installed `rubigen`, making some step forward but hitting this now:

```
pallotron@pallotron-mba:~ $ install_choctop projects/yubiswitch/
You don't have i18n installed in your application. Please add it to your Gemfile and run bundle install
/Users/pallotron/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- i18n (LoadError)
```

**Comment by pallotron** [comment]
lol, i've installed i18n gem and now i'm hitting:

```
pallotron@pallotron-mba:(master) ~/projects/yubiswitch $ install_choctop ./
undefined method `source_index' for Gem:Module
```

Unfortunately I'm a complete Ruby n00b...
